// Mutable singleton state shared across the main-process modules.
// Each consumer requires this once and reads/writes the same object.

module.exports = {
  /** @type {import('electron').BrowserWindow | null} */
  mainWindow: null,
  /** @type {import('electron').BrowserWindow | null} */
  videoWindow: null,
  /** Transparent always-on-top overlay for the seekbar preview thumbnail.
   *  Lives above the mpv video window so the preview isn't clipped behind it.
   *  @type {import('electron').BrowserWindow | null} */
  previewWindow: null,
  /** @type {import('./mpv-controller.js').MpvController | null} */
  mpv: null,
  /** @type {string | null} */
  captureDir: null,
  /** @type {import('./transcode.js').TranscodeJob | null} */
  currentJob: null,
  /** @type {{ x: number, y: number, width: number, height: number } | null} */
  lastVideoBounds: null,
  /** Whether a UI overlay (modal etc.) is currently open in the renderer. */
  overlayActive: false,
  /** Set true once the user confirms quit in the exit popup, so the next
   *  window 'close' is allowed through instead of re-showing the popup. */
  exitConfirmed: false,
  /** File paths passed via argv/second-instance before the current renderer is ready. */
  pendingOpenPaths: [],
  /** True once the current navigation signalled app:rendererReady. */
  rendererReady: false,
  /** Incremented whenever the main frame starts a new navigation. */
  navigationGeneration: 0,
  /** Exact output files approved by a native save dialog (canonical path keys). */
  approvedOutputPaths: new Set(),
  /** Directories approved by the native directory picker (canonical path keys). */
  approvedOutputDirs: new Set(),
  /** Files successfully generated by this app (canonical existing path keys). */
  generatedPaths: new Set(),
  /** All tracked ffmpeg/ffprobe helper processes. */
  childProcesses: new Set(),
  /** IPC operations, including post-process commits and temp cleanup. */
  activeOperations: new Set(),
  /** Renderer intent; temporary overlays/minimize must not overwrite this flag. */
  desiredVideoVisible: false,
  /** Fail-safe timer for the renderer-driven close prompt. */
  quitPromptTimer: null,
  /** Delayed startup warm-up owned by lifecycle cleanup. */
  warmupTimer: null,
  /** App-level shutdown state shared by windows and lifecycle hooks. */
  isQuitting: false,
  cleanupPromise: null,
  cleanupComplete: false,
};
